name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from commits
        uses: Platane/snk@v2
        with:
          github_user_name: itsmeCALVES  # Certifique-se que o nome de usuário esteja correto
          svg_out_path: dist/snake.svg  # O caminho do SVG gerado

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: snake-svg
          path: dist/snake.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
