name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Etapa para fazer o checkout do código
      - uses: actions/checkout@v2

      # Etapa para criar o diretório dist (se não existir)
      - name: Criar diretório dist (se não existir)
        run: mkdir -p dist

      # Etapa para gerar o Snake Game a partir dos commits
      - name: Generate Snake Game from commits
        uses: Platane/snk@master
        with:
          github_user_name: itsmeCALVES  # Substitua pelo seu nome de usuário
          svg_out_path: dist/snake.svg   # Corrigido o parâmetro svg_out_path

      # Etapa para empurrar o Snake Game para o branch do GitHub Pages
      - name: Push Snake Game to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Adiciona o token para autenticação
