name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Garante que o diretório dist exista antes de gerar o Snake Game
      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Generate Snake Game from commits
        uses: Platane/snk@v2
        with:
          github_user_name: itsmeCALVES  # Substitua pelo seu nome de usuário
          svg_out_path: dist/snake.svg

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-artifact@v3  # Versão mais recente
        with:
          name: snake-svg
          path: dist/snake.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: snake-game
